config/routes.rb
Rails.application.routes.draw do
  resources :flowers
  resources :hives
  resources :bees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bee.rb
class Bee < ApplicationRecord
  has_many :flights
  has_many :flowers, through: :bees
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :bee
  belongs_to :flower
end

app/models/flower.rb
class Flower < ApplicationRecord
  has_many :flights
  has_many :bees, through: :flights
end

app/models/hive.rb
class Hive < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bees_controller.rb
class BeesController < ApplicationController
  def index
    @bees = Bee.all
  end

  def new
    @bee = Bee.all
  end

  def show
    @bee = Bee.find(params[:id])
  end

  def edit
    @bee = Bee.find(params[:id])
    @hives = Hive.all
  end



  def update
    @bee = Bee.find(params[:id])
    @bee.update(bee_params)
    redirect_to bees_path
  end

  private

  def bee_params
    params.require(:bee).permit(:name, :queen, :hive_id)
  end

end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  def index
    @flowers = Flower.all
  end

  def new
    @flower = Flower.new
  end

  def show
    @flower = Flower.find(params[:id])
  end

  def edit
    @flower = Flower.find(params[:id])
  end

  def update
    @flower = Flower.update(flower_params)
    redirect_to flower_path(@flower)
  end


  private

    def flower_params
        params.require(:flower).permit(:name, :pollen_capacity, :integer)
    end

end

app/controllers/hives_controller.rb
class HivesController < ApplicationController
    before_action :set_hive, only: [:show, :edit, :update, :delete]
    before_action :set_bees, only:[:new, :edit]

    def index
        @hives = Hive.all
    end

    def show
        @bees = @hive.bees
    end

    def new
        @hive = Hive.new
    end

    def edit
    end

    def create
        hive = Hive.create(hive_params)
        if hive.valid?
            redirect_to hive
        else
            flash[:errors] = hive.errors.full_messages
            redirect_to new_hive_path
        end
    end

    def update
        @hive.update(hive_params)
        if @hive.valid?
            redirect_to @hive
        else
            flash[:errors] = @hive.errors.full_messages
            redirect_to edit_hive_path
        end
    end

    def delete
        @hive.destroy
        redirect_to hives_path
    end

    private
      def set_hive
          @hive = Hive.find(params[:id])
      end

      def hive_params
          params.require(:hive).permit(:name, :honey_type, bee_ids: [])
      end

      def set_bees
          @bees = Bee.all
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/hives_helper.rb
module HivesHelper
end

app/views/bees/_form.erb
  <%= form_for @bee do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :queen %>
    <%= f.check_box :queen %><br>
    <%= f.label :hive_id %>
    <%= f.collection_select :hive_id, @hives, :id, :name %><br>
    <%= f.submit %>
        <% end %>

app/views/bees/edit.erb
      <%= render 'form' %>

app/views/bees/index.html.erb
<h1>this is bee index page</h1>

<% @bees.each do |bee| %>
  <%= link_to bee.name, edit_bee_path(bee) %><br/>

    <% end %>

app/views/bees/new.erb
<h1>this is the bee/new page</h1>

<%= render 'form' %>

app/views/bees/show.erb
  <%= @bee.name %><br/>
  <%= @bee.queen %><br/>

app/views/flowers/_form.erb
<%= form_for @flower do |f| %>
<%= f.label :name %>
<%= f.text_field :name%> </br>
<%= f.label :pollen_capacity %>
<%= f.text_field :pollen_capacity%></br>
<%= f.label :integer%>
<%= f.text_field :integer%>
<%= f.submit %>
<% end %>

app/views/flowers/edit.erb
<%= render 'form' %>

app/views/flowers/index.erb
<h1>this is flower index page</h1>

<% @flowers.each do |flower| %>
  <%= link_to flower.name, flower %><br/>

    <% end %>

app/views/flowers/show.erb
<%= @flower.name %>

app/views/hives/_footer.html.erb
<br>
<%= link_to "See all Hives!", hives_path %><br>
<%= link_to "Add new Hive", new_hive_path %>

app/views/hives/_form.html.erb
<% if flash[:errors] && flash[:errors].length > 0  %>
    <ul><%  flash[:errors].each do |error| %>
        <li> <%= error %></li>
        <% end %>
    </ul>
<% end  %>



<%= form_for @hive do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :honey_type %>
    <%= f.text_field :honey_type %><br>
    <%= f.label "Bees:" %>
    <%= f.collection_check_boxes :bee_ids, @bees, :id, :name %><br>
    <%= f.submit %>
<% end %>

app/views/hives/edit.html.erb
<h1>Edit Hive:</h1>

<%= render "form" %>
<br>
<%= link_to "Go back!", @hive %>

<%= form_tag hive_path(@hive), method "delete" do %>
    <%= submit_tag "Delete Hive" %>
    <% end %>

<%= render "footer" %>

app/views/hives/index.html.erb
<h1>All Hives</h1>

<ul><% @hives.each do |hive| %>
    <li><%= link_to hive.name, hive %> | <%= hive.honey_type %></li>
    <% end  %>
</ul>

 <%= link_to "Create new Hive", new_hive_path %>

app/views/hives/new.html.erb
<h1>Create a new Hive</h1>

<%= render "form" %>

<%= render "footer" %>

app/views/hives/show.html.erb
<h1><%= @hive.name %></h1>

<p>This is a lovely hive. It specialises in <%= @hive.honey_type %> honey.</p>

<p>The bees that belong to this hive are:</p>

<ul><% @bees.each do |bee| %>
    <li><%= link_to bee.name, bee %></li>
    <% end %>
    </ul>
<%= render "footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2BeeExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>